<div class="login">
	<form method="post"  autocomplete="off">
		<input type="hidden" name="id" value="<?=$id?>">
		<div class="recherche">

			<label for="nom">nom :</label>
			<input id="nom" type="text" name="nom" value="<?=$nom?>"placeholder="nom"/>
		</div>
		<div class="recherche">
			<label for="depart">Depart :</label>
			<input id="depart" type="text" name="depart" value="<?=$depart?>"placeholder="Depart"/>
		</div>
		<div class="recherche">
			<label for="destination">Destination :</label>
			<input id="destination" type="text" name="destination" value="<?=$destination?>"placeholder="Destination" />
		</div>
		<div class="recherche">
			<label for="prix">Prix :</label>
			<input id="prix" type="number" name="prix" value="<?=$prix?>"placeholder="prix"/>
		</div>
		<div class="recherche">
			<label for="classe_eco">Classe Echo :</label>
			<input id="classe_eco" type="number" name="classe_eco" value="<?=$classe_eco?>"placeholder="classe eco"/>
		</div>
		<div class="recherche">
			<label for="classe_business">Classe Business :</label>
			<input id="classe_business" type="number" name="classe_business" value="<?=$classe_business?>"placeholder="classe business"/>
		</div>
		<div class="recherche">
			<label for="premiere_classe">Premiere Classe :</label>
			<input id="premiere_classe" type="number" name="premiere_classe" value="<?=$premiere_classe?>"placeholder="premiere classe"/>
		</div>
		<div class="recherche">
			<label for="date">Date :</label>
			<input id="date" type="date" name="date" value="<?=$date?>"placeholder="date"/>
		</div>
		<div class="recherche">
			<label for="resume">Résumer :</label>
			<textarea class="margin-bottom" name="resume"><?=$resume?></textarea>
		</div>
		<div class="recherche">
			<label for="date">url :</label>
			<input id="date" type="url" name="url" value="<?=$url?>"placeholder="http://"/>

			<label class="white" for="nom">nom :</label>
			<input id="nom" type="text" name="nom" placeholder="nom"/>
		</div>
		<div class="recherche">
			<label class="white" for="depart">Depart :</label>
			<input id="depart" type="text" name="depart" placeholder="Depart"/>
		</div>
		<div class="recherche">
			<label class="white" for="destination">Destination :</label>
			<input id="destination" type="text" name="destination" placeholder="Destination" />
		</div>
		<div class="recherche">
			<label class="white" for="prix">Prix :</label>
			<input id="prix" type="number" name="prix" placeholder="prix"/>
		</div>
		<div class="recherche">
			<label class="white" for="classe_eco">Classe Echo :</label>
			<input id="classe_eco" type="number" name="classe_eco" placeholder="classe eco"/>
		</div>
		<div class="recherche">
			<label class="white" for="classe_business">Classe Business :</label>
			<input id="classe_business" type="number" name="classe_business" placeholder="classe business"/>
		</div>
		<div class="recherche">
			<label class="white" for="premiere_classe">Premiere Classe :</label>
			<input id="premiere_classe" type="number" name="premiere_classe" placeholder="premiere classe"/>
		</div>
		<div class="recherche">
			<label class="white" for="date">Date :</label>
			<input id="date" type="date" name="date" placeholder="date"/>
		</div>
		<div class="recherche">
			<label class="white" for="resume">Résumer :</label>
			<textarea name="resume"></textarea>
		</div>
		<div class="recherche">
			<label class="white" for="date">url :</label>
			<input id="date" type="url" name="url" placeholder="http://"/>

		</div>
		<div class="recherche">
			<button type="submit" name="action" value="<?=$action?>">envoyer</button>
		</div>
	</form>
	<?php require 'apps/error.php'; ?>
</div>
