<div class="container">
	<div class="floatLeft">
		<div>
			<div>
				<p>Images départs</p>
			</div>
			<div>
				<p>Images destinations</p>
			</div>
			<div>
				<p>Images prestations</p>
			</div>
		</div>
	</div>
	<div class="floatRight">
		<div>
			<p>Texte de résumé</p>
			<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
		</div>
	</div>
</div>


<form method="post">
    <div>
        <input type="radio" name="classBusiness" value="Classe Business"/>
        <p>Business</p> 
    </div>

     <div>
        <input type="radio" name="classPremiere" value="Premiere Classe"/>
        <p>Premiere</p> 
    </div>

   	<div>
        <input type="radio" name="classEconomique" value="Classe Economique"/>
        <p>Economique</p> 
    </div>


    <div>
    	<div class="">
        	<p>Conditions générales de vente 
       		<br></br>
       		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
       		</p>
    	</div>
    	<div class="">
            <input type="radio" name="CGV" value="CGV"/> 
        </div>
        <p>J'ai lu les conditions</p>

		<div>
			<button type="submit">Je valide ma commande</button>
		</div>

    </div>
</form>

