
<h1 style="color:#000;"><?=htmlentities($voyage['nom'])?></h1>

<p class="lead">
    date du voyage : <a href="#"><?=htmlentities($voyage['date'])?></a>
</p>

<p>Départ : <span class="glyphicon glyphicon-qrcode"></span><?=htmlentities($voyage['depart'])?></p>

<hr>

<p>Destination : <span class="glyphicon glyphicon-time"></span><?=htmlentities($voyage['destination'])?></p>

<hr>

<p>Prix du voyage : <?=htmlentities($voyage['prix']) . ".00 €" ?></p>

<hr>

<p>Résumé du voyage : <?=htmlentities($voyage['resume'])?></p>

<a class="btn btn-primary" href="index.php?page=resumer.php">En savoir plus</a>

<hr>

<a class="btn btn-primary" href="index.php?page=tarif&id=<?=htmlentities($voyage['id'])?>">choisir</a>
