	<main class="container">
		<header class="header_user">
			<a href="http://localhost/Mission-to-Mars/MVC/index.php?page=home">
				<div class="centauriTitle">
					<h1>CENTAURI STELLAIRE</h1>
					<h2>TOUR OPERATOR POUR L'ESPACE</h2>
				</div>
			</a>
			<nav>
				<ul class="nav">
					<li>
					<a href="index.php?page=voyage">ACHETER UN BILLET</a>
				</li>
					<li>
						<a href="index.php?page=recherche">RECHERCHE</a>
					</li>
					<li>
						<a href="index.php?page=logout">LOGOUT</a>
					</li>
					<li id="navMenuButton">
						<a href="#"><?=$_SESSION['email']?></a>
					</li>
				</ul>
			</nav>
		</header>	

