	<main class="container">
		<header>
			<a href="http://localhost/Mission-to-Mars/MVC/index.php?page=home">
				<div class="centauriTitle">
					<h1>CENTAURI STELLAIRE</h1>
					<h2>TOUR OPERATOR POUR L'ESPACE</h2>
				</div>
			</a>
			<nav>
				<ul class="nav">
					<li>
						<a href="index.php?page=home">ACHETER UN BILLET</a>
					</li>
					<li>
						<a href="index.php?page=recherche">RECHERCHE</a>
					</li>
					<li>
						<a href="index.php?page=login-register">LOGIN</a>
					</li>
					<li>
						<a href="index.php?page=creation">CREATION</a>
					</li>
				</ul>
			</nav>
		</header>