<main class="container">
	<header>
		<div class="centauriTitle">
			<h1>CENTAURI STELLAIRE</h1>
			<h2>TOUR OPERATOR POUR L'ESPACE</h2>
		</div>
		<nav>
			<ul class="nav">
				<li>
					<a href="index.php?page=home">ACHETER UN BILLET</a>
				</li>
				<li>
					<a href="index.php?page=recherche">RECHERCHE</a>
				</li>
				<li>
					<a href="index.php?page=logout">LOGOUT</a>
				</li>
				<li id="navMenuButton">
					<a href="#"><?=$_SESSION['email']?></a>
				</li>
			</ul>
		</nav>
	</header>	