

		<main class="container">
			<header>
				<h1>CENTAURI STELLAIRE</h1>
				<h2>TOUR OPERATOR POUR L'ESPACE</h2>
				<img class="logo nav" src="logo/logo.png" alt="logo"/>
			<nav>
				<ul class="nav">
					<li>
						<a href="index.php?page=home">ACHETER UN BILLET</a>
					</li>
					<!--<li>ENREGISTREMENT</li>-->
					<li>
						<a href="index.php?page=login">LOGIN</a>
					</li>
					<li>
						<a href="index.php?page=register">REGISTER</a>
					</li>
				</ul>
			</nav>
		</header>