	<main class="container">
		<header>
			<h1>CENTAURI STELLAIRE</h1>
			<h2>TOUR OPERATOR POUR L'ESPACE</h2>
			<a href="http://localhost/Mission-to-Mars/MVC/index.php?page=home"><img class="logo nav" src="./public/logo/logo.png" alt="logo"/></a>
			<nav>
				<ul class="nav">
					<li>
						<a href="index.php?page=home">ACHETER UN BILLET</a>
					</li>
					<li>
						<a href="index.php?page=recherche">RECHERCHE</a>
					</li>
					<li>
						<a href="index.php?page=logout">LOGOUT</a>
					</li>
					<li id="navMenuButton">
						<a href="#"><?=$_SESSION['email']?></a>
					</li>
					<li>
						<a href="index.php?page=creation">creation</a>
					</li>
				</ul>
			</nav>
		</header>