	<main class="container">
		<header class="header_in">
			<a href="http://localhost/Mission-to-Mars/MVC/index.php?page=home">
				<div class="centauriTitle">
					<h1>CENTAURI STELLAIRE</h1>
					<h2>TOUR OPERATOR POUR L'ESPACE</h2>
				</div>
			</a>
			<nav>
				<ul class="nav">
					<li>
						<a href="index.php?page=voyage" class="gradAndBoxShad">NOS VOYAGES</a>
					</li>
					<li>
						<a href="index.php?page=recherche" class="gradAndBoxShad">RECHERCHE</a>
					</li>
					<li>
						<a href="index.php?page=logout" class="gradAndBoxShad">LOGOUT</a>
					</li>
					<li id="navMenuButton">
						<a href="#" class="gradAndBoxShad"><?=htmlentities($_SESSION['email'])?></a>
					</li>
					<li>
						<a href="index.php?page=creation" class="gradAndBoxShad">creation</a>
					</li>
				</ul>
				<?php require 'apps/error.php' ?>
			</nav>
		</header>
