<article>
	<div class="article">
		<h3>La mer de la tranquillité : 2500€ une journée sur la LUNE.</h3>

		<img src="./public/images/pub.jpg" alt="pub">
		
		<h3>UNE CROISIERE STELLAIRE DE UN AN POUR 25 000€ !</h3>
		<p>
			Un billet pour l'Axiom, c'est le point de départ d’un séjour sans limite dans le systeme solaire qui ne dort jamais. Tous les guides de voyage de l'espace l'attestent : une top destination à voir au moins une fois dans sa vie. CENTAURI STELLAIRE propose des vols quotidiens au départ de la Terre.
		</p>
		<p>
			La première image qui marque les esprits lors d’un voyage dans le systeme solaire, ce sont les étoiles pour les amateurs d'astronomie. Mercure, Venus ou encore Mars... que l’on admire. Mercure, station balnéaire,
			des températures de -173 °C la nuit et 427 °C le jour à l'équateur, idéal pour avoir un bronzage parfait.    
		</p>
		<P>	
		<div class="mini_article">
			<img src="./public/images/femme.jpg" class="img_article" alt="femme">
		</div>
			Un vol pour Mars ? c'est le début d’une plongée dans une destination culturelle incontournable. les plus belle maisons closes réputés sur terre et ces femmes à trois seins. De même que les musées qui peuplent la ville comme Barsoom, le Metropolitan Museum of Art ou encore le Guggenheim. Barsoom abrite de nombreuses galeries d'art et des antiquaires qui cachent de nombreux trésors. Prêt à vivre l’expérience de la ville qui ne dort jamais jusqu’au bout de la nuit ? 
		</P>
		<p>
			Les night-clubs tendance de Barsoom vous emmèneront jusqu’au petit matin...
			Lors de votre séjour dans la « Big station » offrez-vous un véritable tour de l'univers ! Une pizza à Little Italy sur les lunes de Saturne , un wok à Chinatown, un bortsch à Little Odessa… Pour un séjour à la Jupiteriene, privilégiez un brunch à Meatpacking, puis profitez de la verdure légendaire de Central Pluton. On en oublierait presque la station spatiale internationale, le symbole de votre voyage dans l'espace !
		</p>
		<h3>Le musée de l'I.S.S : 499€ la journée.</h3>
		<div class="mini_article">
			<img src="./public/images/ss-internationale.jpg" alt="ss-internationale">
		</div>

		<p>
			Une station spatiale, dans le domaine de l'astronautique, est une installation spatiale en orbite ou déposée sur un astre, ne disposant pas de moyens de propulsion autonomes ou ne disposant que de moyens de propulsion réduits, et destinée à assurer une ou plusieurs missions déterminées avec une certaine permanence.
		</p>
		<p>
			Jusqu'à présent, seules des stations spatiales destinées à être en orbite terrestre basse ont été construites. Elles sont désignées comme « stations orbitales ».
		</p>
		<p>
			Les stations actuelles et les précédentes ont été conçues pour rester en orbite de quelques semaines à plusieurs années. La seule station encore en activité en 2015 est la Station spatiale internationale. Les stations précédentes étaient celles des programmes soviétiques Almaz, Saliout et Mir, ainsi que la station spatiale américaine Skylab.
		</p>
	</div>
	<div class="info">
		<h3 class="color">Édito / Août 3016 :</h3>
		<img class="img" src="./public/images/solar.jpg" alt="solar">
		<p class="white">
			Que l’on soit en vacances ou pas, le mois d’août est l’occasion de prendre un peu de recul ou de regarder plus loin, autour… pour mieux se projeter. Pourquoi pas sur la LUNE  pour y vivre la Centauri-Stellaire Expérience ? En parcourant notre carnet de voyages, peut-être aurez-vous envie de découvrir les satellites de JUPITER pour y observer de merveilleux panoramas ? Ou alors MARS ou MERCURE pour y observer des paysages incroyables… En août, c’est aussi le moment de penser aux week-ends : allez découvrir VENUS dans les coulisses des distilleries, ou PLUTON, au plus loin du systeme solaire.
		</p>
		<h3 class="color">Les vaisseaux :</h3>
		<img class="img" src="./public/images/axiom.jpg" alt="axiom">
		<p class="white">
			La cinquième génération de vaisseau est une classification générale des vaisseaux spatial à partir des années 2516 jusqu’à nos jours. Elle représente des concepts et designs développés dans les années 2310 et 2402.

			Le seul représentant en service de cette génération est l'Axiom produit à 185 exemplaires, en comprenant les prototypes, et dont la production a été abandonnée en 2499.

			La Chine et la Russie développeraient actuellement leur propre vaisseau de cette génération.
		</p>
	</div>
</article>