<div class="container">

	<h1 style="color:#000;"><?=$nom?></h1>

	<p class="lead">
	    date du voyage : <a href="#"><?=$date?></a>
	</p>

	<p>Départ : <span class="glyphicon glyphicon-qrcode"></span><?=$depart?></p>

	<hr>

	<p>Destination : <span class="glyphicon glyphicon-time"></span><?=$destination?></p>

	<hr>

	<p>Prix du voyage : <?=$prix . ".00 €" ?></p>

	<hr>

	<p>Résumé du voyage : <?=$resume?></p>

	<a class="btn btn-primary" href="index.php?page=article&id=<?=$destination?>">En savoir plus</a>

	<hr>
</div>