

<div class="login">
	<h2>Je m'identifie pour y accèder :</h2>
	<form method="post">
		<!-- login -->
		<div>
			<label class="white" for="aliaslogin">Email :</label>
			<input id="aliaslogin" type="email" name="email" placeholder=""/>
		</div>
		<!-- password -->
		<div>
			<label class="white" for="aliasmdp">Password :</label>
		    <input id="aliasmdp" type="password" name="password"/>
		</div>
		<!-- Connexion -->
		<div>
			<button type="submit" name="login" value="login">Connexion</button>
		</div>
	</form>
</div>

<div class="login">
	<h2>Je crée un compte utilisateur :</h2>
	<form method="post">	
    	<!-- nom -->
    	<div>
    		<label class="white" for="aliasnom">Nom :</label>
    		<input id="aliasnom" type="text" name="nom" placeholder="Votre NOM"/>
		</div>
		<!-- prenom -->
		<div>
    		<label class="white" for="aliasprenom">Prénom :</label>
    		<input id="aliasprenom" type="text" name="prenom" placeholder="Votre PRENOM"/>
		</div>
		<!-- adresse -->
		<p class="white">Remplir l'adresse de facturation :</p>
		<div>
    		<label class="white" for="aliasrue">N°, Rue ou voie :</label>
    		<input id="aliasprue" type="text" name="adresse" placeholder="N°, Rue ou voie :"/>
		</div>
		<div>
    		<label class="white" for="aliascp">Code postal :</label>
    		<input id="aliaspcp" type="text" name="cp" placeholder="00000"/>
		</div>
		<div>
    		<label class="white" for="aliasville">Ville :</label>
    		<input id="aliasville" type="text" name="ville" placeholder="Ville"/>
		</div>
		<!-- telephone -->
		<div>
	    	<label class="white" for="aliastel">Téléphone :</label>
	    	<input id="aliastel" type="text" name="tel" placeholder="+33"/>
		</div>
		<!-- e-mail -->
		<div>
			<label class="white" for="aliasemail">Adresse e-mail :</label>
			<input id="aliasemail" type="email" name="email" placeholder="Votre EMAIL"/>
		</div>
		<!-- password -->
		<div>
			<label class="white" for="aliasmdp">Password :</label>
		    <input id="aliasmdp" type="password" name="password"/>
	    </div>
	    <div>
	    	<label class="white" for="aliascmdp">Comfirm.Password :</label>
		    <input id="aliascmdp" type="password" name="password2"/>
		</div>
		<!-- valid -->
		<div>
			<button type="submit" name="register" value="register">Envoyer</button>
		</div>
	</form>
</div>