<div class="container">

	<?php require 'apps/error.php'; ?>
	<div class="login">
		<form method="post">	
			<div class="depart">
				<label for="depart">Selectionner votre ville de départ : </label>
				<select name="depart" class="form-control">
					<?php echo $choixdepart; ?>
				</select>
			</div>
			<div class="destination">
				<label for="destination">Selectionner votre planète de déstination : </label>
				<select name="destination" class="form-control">
				  	<?php echo $choixdestination; ?>
				</select>
			</div>
			<button type="submit" class="button">Valider</button>

<div class="container">

	<?php require 'apps/error.php'; ?>


		<?php require 'apps/list.php'; ?>
	</div>
</div>

