<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>Centauri-Stellaire</title>
		<link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet"/>
		<link type="text/css" rel="stylesheet" href="public/styles/style.css"/>
	</head>
	<body>
		<?php
			require('apps/header.php');
			require('apps/content.php');
			require('apps/footer.php');
		?>
	</body>
</html>