<div class="gradAndBoxShad voyage">
	<?php if($voyage["url"] != "") : ?>
		<img src="<?=htmlentities($voyage["url"])?>" alt=""> 
	<?php endif; ?>
	<h1 style="color:#000;"><?=htmlentities($voyage['nom'])?></h1>

	<p class="lead">
	    date du voyage <a href="#"><?=htmlentities($voyage['date'])?></a>
	</p>

	<p>Départ :<span class="glyphicon glyphicon-qrcode"></span><?=htmlentities($voyage['depart'])?></p>

	<hr>

	<p>Destination :<span class="glyphicon glyphicon-time"></span> <?=htmlentities($voyage['destination'])?></p>

	<hr>

	<p>Prix du voyage : <?=htmlentities($voyage['prix'])?></p>

	<hr>



	<p>Résumé du voyage : <?=htmlentities($voyage['resume'])?></p>

	<hr>


	



	<?php require "apps/voyage_admin.php";?>
	<?php require "apps/comment.php";?>
	<p>note moyenne : <?=htmlentities($voyage['note'])?></p>

	<form  method="POST" >
		
		<input type="hidden" name="id" value="<?=htmlentities($voyage["id"])?>">
		<input type="hidden" name="action" value="comment">
		<textarea class="commentVoyage"  name="comment" ></textarea>
		<div>
			Notez ce voyage
			<label for="note_<?= $voyage["id"] ?>_1">
				<input type="radio" name="note" id="note_<?= $voyage["id"] ?>_1" value="1">1
			</label>
			<label for="note_<?= $voyage["id"] ?>_2">
				<input type="radio" name="note" id="note_<?= $voyage["id"] ?>_2" value="2">2
			</label>
			<label for="note_<?= $voyage["id"] ?>_3">
				<input type="radio" name="note" id="note_<?= $voyage["id"] ?>_3" value="3" checked>3
			</label>
			<label for="note_<?= $voyage["id"] ?>_4">
				<input type="radio" name="note" id="note_<?= $voyage["id"] ?>_4" value="4">4
			</label>
			<label for="note_<?= $voyage["id"] ?>_5">
				<input type="radio" name="note" id="note_<?= $voyage["id"] ?>_5" value="5">5
			</label>
		</div>
		<!-- <input type="number" name="note" > -->
		<button class="btn btn-default submitComment" type="submit">Envoyer</button>
	</form>
	<a class="btn btn-primary" href="index.php?page=tarif&id=<?=htmlentities($voyage['id'])?>">choisir</a>
</div>