<?=$error?>
<img src="<?=$voyage["url"]?>">
<h1 style="color:#000;"><?=$voyage['nom']?></h1>

<p class="lead">
    date du voyage <a href="#"><?=$voyage['date']?></a>
</p>

<p>Départ :<span class="glyphicon glyphicon-qrcode"></span><?=$voyage['depart']?></p>

<hr>

<p>Destination :<span class="glyphicon glyphicon-time"></span> <?=$voyage['destination']?></p>

<hr>

<p>Prix du voyage : <?=$voyage['prix']?></p>

<hr>

<p>Résumé du voyage : <?=$voyage['resume']?></p>
<hr>
<?php require "apps/voyage_admin.php";?>
<?php require "apps/comment.php";?>


<form  method="POST" >
	
	<input type="hidden" name="id" value="<?=$voyage["id"]?>">
	<input type="hidden" name="action" value="comment">
	<textarea class="form-control" rows="10" name="comment" ></textarea>
	<button class="btn btn-default" type="submit">Envoyer</button>
</form>


<hr>